FROM python:3.10-slim

WORKDIR /app

COPY api-gateway/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY api-gateway /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
