FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/script.js /usr/share/nginx/html/script.js
COPY frontend/style.css /usr/share/nginx/html/style.css

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
